name: muppin_app
description: New Generation Mobile Application

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1
  mailer: ^6.0.1
  shared_preferences: ^2.2.1
  fluttertoast: ^8.2.2
  http: ^1.1.0
  faker: ^2.1.0
  url_launcher: ^6.1.14
  intl: ^0.18.1
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  flutter_settings_ui: ^2.0.1
  awesome_dialog: ^3.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  image: ^4.1.3
  provider: ^6.1.1
  chat_bubbles: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/default.png
    - assets/images/chat_bg.jpeg

    - assets/badges/bughunter.png
    - assets/badges/erkendonemdestekcisi.png
    - assets/badges/premium.png
    - assets/badges/admin.png

    - assets/socials/instagram.png
    - assets/socials/twitter.png
    - assets/socials/youtube.png
    - assets/socials/discord.png